default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: willemse_development

test:
  <<: *default
  database: willemse_test

production:
  <<: *default
  database: willemse_production
  username: willemse
  password: <%= ENV['WILLEMSE_DATABASE_PASSWORD'] %>

sql_server:
  adapter: sqlserver
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  host: 83.206.117.85
  database: RCFactory
  username: <%= ENV['SQL_SERVER_DATABASE_USERNAME'] %>
  password: <%= ENV['SQL_SERVER_DATABASE_PASSWORD'] %>